import { useEffect, useState } from 'react';
import { ArrowRight, BrainCircuit, ChartNoAxesCombined, Layers3, MessageCircle, Sparkles } from 'lucide-react';
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useNavigate } from 'react-router-dom';

type AnalyticsData = { totalMessages: number; totalConcepts: number; avgMastery: number; masteryGrade: string; totalCards: number; sessionCount: number; studyTimeData: Array<{ name: string; messages: number; concepts: number }>; subjectMastery: Array<{ name: string; score: number }>; recentConcepts: Array<{ tag: string; question: string; mastery: number }> };

export default function Analytics() {
  const [data, setData] = useState<AnalyticsData | null>(null);
  const navigate = useNavigate();
  useEffect(() => { fetch('/api/analytics').then((r) => r.json()).then(setData).catch(() => undefined); }, []);
  if (!data) return <div className="page page-enter"><div className="panel p-8 text-sm text-slate-600">Loading your study signals…</div></div>;
  const metrics = [['Messages', data.totalMessages, MessageCircle, 'Conversation turns'], ['Concepts', data.totalConcepts, Sparkles, 'Captured for review'], ['Deck', data.totalCards, Layers3, 'Cards in your workspace'], ['Mastery', data.avgMastery ? `${data.avgMastery}%` : '—', BrainCircuit, data.avgMastery ? `Current grade ${data.masteryGrade}` : 'Review cards to build this signal']];
  return <div className="page page-enter space-y-5">
    <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Signals from your workspace</p><h1 className="display-title mt-4 text-5xl sm:text-6xl">Learning, in motion.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-slate-600">These are computed from the sessions, cards, and courses in this workspace.</p></div><button className="button-secondary" onClick={() => navigate('/sessions')}>Return to study <ArrowRight size={16} /></button></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, Icon, copy]) => { const MetricIcon = Icon as typeof MessageCircle; return <article key={String(label)} className="panel p-5"><div className="flex items-start justify-between"><p className="font-mono text-[10px] uppercase tracking-[.12em] text-slate-500">{label}</p><MetricIcon size={18} className="text-ink" /></div><p className="mt-8 font-display text-4xl font-bold tracking-[-.07em] text-ink">{value}</p><p className="mt-2 text-xs text-slate-500">{copy as string}</p></article>; })}</section>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
      <section className="panel p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="eyebrow">Learning weather</p><h2 className="section-title mt-3">Seven-day activity</h2></div><ChartNoAxesCombined size={21} className="text-slate-500" /></div><div className="mt-7 h-72"><ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={288} initialDimension={{ width: 1, height: 288 }}><BarChart data={data.studyTimeData} margin={{ top: 8, right: 0, left: -28, bottom: 0 }}><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#667085', fontSize: 10, fontWeight: 700 }} /><YAxis hide /><Tooltip cursor={{ fill: 'rgba(140,186,255,.12)' }} contentStyle={{ borderRadius: 14, border: '1px solid #dce0d5', boxShadow: 'none' }} /><Bar dataKey="messages" fill="#8cbaff" radius={[7, 7, 0, 0]} barSize={22} /><Bar dataKey="concepts" fill="#8bdcba" radius={[7, 7, 0, 0]} barSize={22} /></BarChart></ResponsiveContainer></div><div className="mt-4 flex gap-4 font-mono text-[10px] uppercase tracking-wider text-slate-500"><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-sky" />Messages</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-mint" />Concepts</span></div></section>
      <section className="panel-dark p-6 sm:p-8"><p className="eyebrow text-white/65 before:bg-mint">Course signals</p><h2 className="section-title mt-3 text-white">Mastery by course</h2>{data.subjectMastery.length ? <div className="mt-8 space-y-6">{data.subjectMastery.map((subject) => <div key={subject.name}><div className="mb-2 flex items-center justify-between gap-4"><span className="truncate text-sm font-bold">{subject.name}</span><span className="font-mono text-[10px] text-mint">{subject.score}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/13"><div className="h-full rounded-full bg-mint transition-[width] duration-300" style={{ width: `${subject.score}%` }} /></div></div>)}</div> : <p className="mt-8 max-w-sm text-sm leading-7 text-white/70">Courses you create from PDFs will appear here.</p>}</section>
    </div>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <section className="panel p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="eyebrow">Collected in conversation</p><h2 className="section-title mt-3">Recent concepts</h2></div><button className="icon-button" onClick={() => navigate('/flashcards')} aria-label="Open flashcards"><ArrowRight size={17} /></button></div>{data.recentConcepts.length ? <div className="mt-7 space-y-3">{data.recentConcepts.map((concept) => <button key={`${concept.tag}-${concept.question}`} onClick={() => navigate('/flashcards')} className="flex w-full items-center justify-between gap-4 rounded-2xl bg-mist/70 p-4 text-left transition-colors hover:bg-sun/40"><div className="min-w-0"><p className="font-mono text-[9px] uppercase tracking-[.1em] text-slate-500">{concept.tag}</p><p className="mt-1 truncate text-sm font-extrabold text-ink">{concept.question}</p></div><span className="shrink-0 font-mono text-[10px] text-slate-500">{concept.mastery}%</span></button>)}</div> : <div className="mt-7 rounded-2xl bg-mist/70 p-6"><p className="font-bold text-ink">No concepts collected yet.</p><p className="mt-1 text-sm text-slate-600">As you study, useful ideas from chat can land in your deck.</p></div>}</section>
      <section className="panel p-6 sm:p-8"><p className="eyebrow">Session rhythm</p><h2 className="section-title mt-3">Extraction rate</h2><div className="mt-8 flex items-end gap-6"><div className="grid h-32 w-32 shrink-0 place-items-center rounded-full border-[12px] border-sky/35 bg-sky/10"><div className="text-center"><p className="font-display text-4xl font-bold tracking-[-.08em] text-ink">{data.sessionCount ? (data.totalConcepts / data.sessionCount).toFixed(1) : '—'}</p><p className="font-mono text-[8px] uppercase tracking-[.1em] text-slate-500">per session</p></div></div><p className="max-w-xs text-sm leading-7 text-slate-600">{data.sessionCount ? `${data.totalConcepts} concepts have been extracted over ${data.sessionCount} session${data.sessionCount === 1 ? '' : 's'}.` : 'Start a session to build a picture of how your study space is evolving.'}</p></div></section>
    </div>
  </div>;
}
