import { FormEvent, useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowRight, BrainCircuit, Check, ChevronLeft, Plus, RotateCcw, Search, Sparkles, X } from 'lucide-react';

type Card = { id: number; tag: string; q: string; a: string; mastery: number; source: 'ai_chat' | 'pdf' | 'manual' };
type Rating = 'again' | 'hard' | 'easy';

function ReviewRoom({ cards, onClose }: { cards: Card[]; onClose: (cards: Card[]) => void }) {
  const [localCards, setLocalCards] = useState(cards.map((card) => ({ ...card })));
  const [index, setIndex] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const [ratings, setRatings] = useState<Rating[]>([]);
  const [saving, setSaving] = useState(false);
  const [done, setDone] = useState(false);
  const card = localCards[index];
  const rate = async (rating: Rating) => {
    if (!card || saving) return;
    const delta = rating === 'again' ? -20 : rating === 'hard' ? 5 : 15;
    const snapshot = localCards;
    const updated = localCards.map((item) => item.id === card.id ? { ...item, mastery: Math.min(100, Math.max(0, item.mastery + delta)) } : item);
    setLocalCards(updated); setSaving(true);
    try { const response = await fetch(`/api/flashcards/${card.id}/review`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rating }) }); if (!response.ok) throw new Error('Review failed'); setRatings((items) => [...items, rating]); if (index === localCards.length - 1) setDone(true); else { setFlipped(false); window.setTimeout(() => setIndex((value) => value + 1), 160); } } catch { setLocalCards(snapshot); } finally { setSaving(false); }
  };
  if (done) return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/70 p-4 backdrop-blur-md"><section className="panel w-full max-w-md p-8 text-center sm:p-10"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-mint text-ink"><Check size={25} /></div><h2 className="mt-6 font-display text-3xl font-bold tracking-[-.06em] text-ink">Review complete.</h2><p className="mt-3 text-sm leading-6 text-slate-600">You reviewed {ratings.length} card{ratings.length === 1 ? '' : 's'} in this pass.</p><div className="mt-7 grid grid-cols-3 overflow-hidden rounded-2xl border border-line">{(['easy', 'hard', 'again'] as Rating[]).map((rating) => <div key={rating} className="bg-mist/55 p-4"><p className="font-display text-2xl font-bold tracking-[-.06em] text-ink">{ratings.filter((item) => item === rating).length}</p><p className="mt-1 font-mono text-[9px] uppercase text-slate-500">{rating}</p></div>)}</div><button className="button-primary mt-8 w-full" onClick={() => onClose(localCards)}>Return to deck <ArrowRight size={16} /></button></section></div>;
  return <div className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-ink/85 p-4 backdrop-blur-md"><div className="mb-5 flex w-full max-w-xl items-center justify-between text-white"><span className="font-mono text-[10px] uppercase tracking-[.12em]">Card {index + 1} / {localCards.length}</span><button className="icon-button !border-white/18 !bg-white/10 !text-white hover:!bg-white/20" onClick={() => onClose(localCards)} aria-label="Exit review"><X size={18} /></button></div><div className="h-1.5 w-full max-w-xl overflow-hidden rounded-full bg-white/15"><div className="h-full bg-mint transition-[width] duration-300" style={{ width: `${(index / localCards.length) * 100}%` }} /></div><div className="mt-6 w-full max-w-xl" style={{ perspective: '1000px' }}><motion.button type="button" onClick={() => setFlipped((value) => !value)} animate={{ rotateY: flipped ? 180 : 0 }} transition={{ duration: .32, ease: 'easeOut' }} className="relative min-h-[340px] w-full text-left" style={{ transformStyle: 'preserve-3d' }} aria-label="Flip flashcard"><div className="absolute inset-0 flex flex-col justify-between rounded-[2rem] bg-paper p-8 shadow-2xl" style={{ backfaceVisibility: 'hidden' }}><div className="flex items-center justify-between"><span className="rounded-full bg-sky/25 px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-ink">{card.tag}</span><Sparkles size={18} className="text-slate-500" /></div><p className="mx-auto max-w-lg text-center font-display text-3xl font-bold leading-tight tracking-[-.055em] text-ink">{card.q}</p><p className="text-center text-xs text-slate-500">Select to reveal the answer</p></div><div className="absolute inset-0 flex flex-col justify-between rounded-[2rem] bg-sun p-8 shadow-2xl" style={{ backfaceVisibility: 'hidden', transform: 'rotateY(180deg)' }}><span className="font-mono text-[10px] uppercase tracking-[.12em] text-ink/60">Answer</span><p className="mx-auto max-w-lg text-center font-display text-2xl font-bold leading-tight tracking-[-.055em] text-ink">{card.a}</p><span className="text-center text-xs text-ink/60">Choose a rating below</span></div></motion.button></div>{flipped && <div className="mt-6 grid w-full max-w-xl grid-cols-3 gap-3"><button disabled={saving} onClick={() => rate('again')} className="min-h-12 rounded-2xl border border-coral/40 bg-coral/20 px-3 text-sm font-extrabold text-ink transition-colors hover:bg-coral/35">Again</button><button disabled={saving} onClick={() => rate('hard')} className="min-h-12 rounded-2xl border border-white/16 bg-white/10 px-3 text-sm font-extrabold text-white transition-colors hover:bg-white/18">Hard</button><button disabled={saving} onClick={() => rate('easy')} className="min-h-12 rounded-2xl bg-mint px-3 text-sm font-extrabold text-ink transition-colors hover:bg-[#a8edcf]">Easy</button></div>}</div>;
}

export default function Flashcards() {
  const [cards, setCards] = useState<Card[]>([]); const [search, setSearch] = useState(''); const [reviewing, setReviewing] = useState(false); const [adding, setAdding] = useState(false); const [saving, setSaving] = useState(false); const [card, setCard] = useState({ tag: '', q: '', a: '' });
  useEffect(() => { fetch('/api/flashcards').then((r) => r.json()).then(setCards).catch(() => undefined); }, []);
  const queue = [...cards].filter((item) => item.mastery < 100).sort((a, b) => a.mastery - b.mastery);
  const visible = cards.filter((item) => `${item.tag} ${item.q} ${item.a}`.toLowerCase().includes(search.toLowerCase()));
  const addCard = async (event: FormEvent) => { event.preventDefault(); if (!card.q.trim() || !card.a.trim()) return; setSaving(true); try { const response = await fetch('/api/flashcards', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(card) }); if (!response.ok) throw new Error('Could not save card'); const added = await response.json(); setCards((items) => [added, ...items]); setCard({ tag: '', q: '', a: '' }); setAdding(false); } finally { setSaving(false); } };
  return <div className="page page-enter space-y-5">{reviewing && queue.length > 0 && <ReviewRoom cards={queue} onClose={(updated) => { setCards((items) => items.map((item) => updated.find((change) => change.id === item.id) ?? item)); setReviewing(false); }} />}
    <section className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="eyebrow">Memory garden</p><h1 className="display-title mt-4 text-5xl sm:text-6xl">Your deck, alive.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-slate-600">Review what the workspace has collected, then add your own cards when an idea deserves to stay close.</p></div><div className="flex flex-wrap gap-3"><button className="button-secondary" onClick={() => setAdding(true)}><Plus size={17} />New card</button>{queue.length > 0 && <button className="button-primary" onClick={() => setReviewing(true)}><RotateCcw size={17} />Review {queue.length}</button>}</div></section>
    <section className="grid gap-4 sm:grid-cols-3">{[['All cards', cards.length, 'bg-sky/25'], ['In bloom', cards.filter((item) => item.mastery >= 80).length, 'bg-mint'], ['To revisit', queue.length, 'bg-sun']].map(([label, value, color]) => <div key={String(label)} className="panel flex items-center justify-between p-5"><div><p className="font-mono text-[10px] uppercase tracking-[.11em] text-slate-500">{label}</p><p className="mt-2 font-display text-3xl font-bold tracking-[-.06em] text-ink">{value}</p></div><span className={`h-9 w-9 rounded-full ${color}`} /></div>)}</section>
    <section className="panel p-4 sm:p-6"><label className="search-field !w-full !bg-mist/65" aria-label="Search flashcards"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search questions, answers, or tags" /></label></section>
    {cards.length ? <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><AnimatePresence>{visible.map((item) => <motion.article key={item.id} layout initial={{ opacity: 0, scale: .98 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .98 }} className="panel group flex min-h-[250px] flex-col p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-mist px-3 py-1 font-mono text-[9px] uppercase tracking-wider text-slate-600">{item.tag || 'General'}</span><span className="font-mono text-[9px] uppercase tracking-wider text-slate-500">{item.source.replace('_', ' ')}</span></div><h2 className="mt-8 font-display text-2xl font-bold leading-tight tracking-[-.055em] text-ink">{item.q}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-600 opacity-70 transition-opacity group-hover:opacity-100">{item.a}</p><div className="mt-auto border-t border-line pt-5"><div className="flex items-center justify-between font-mono text-[10px] text-slate-500"><span>Mastery</span><span>{item.mastery}%</span></div><div className="progress-track mt-2"><div className="progress-fill" style={{ width: `${item.mastery}%` }} /></div></div></motion.article>)}</AnimatePresence></section> : <section className="panel mx-auto max-w-2xl p-8 text-center sm:p-12"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-mint text-ink"><BrainCircuit size={25} /></div><h2 className="mt-6 font-display text-3xl font-bold tracking-[-.06em] text-ink">Nothing planted yet.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-7 text-slate-600">Cards appear from a PDF, from meaningful moments in chat, or from a card you create yourself.</p><button className="button-primary mt-7" onClick={() => setAdding(true)}><Plus size={17} />Create a card</button></section>}
    {adding && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/50 p-4 backdrop-blur-sm"><motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="panel w-full max-w-lg p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="eyebrow">Add to your deck</p><h2 className="section-title mt-3">New flashcard</h2></div><button className="icon-button" onClick={() => setAdding(false)} aria-label="Close form"><X size={17} /></button></div><form className="mt-7 space-y-4" onSubmit={addCard}><label className="block text-sm font-bold text-ink">Tag<input value={card.tag} onChange={(event) => setCard({ ...card, tag: event.target.value })} className="mt-2 w-full rounded-xl border border-line bg-mist/55 px-3 py-3 text-sm outline-none focus:border-ink" placeholder="Optional category" /></label><label className="block text-sm font-bold text-ink">Question<textarea required value={card.q} onChange={(event) => setCard({ ...card, q: event.target.value })} className="mt-2 min-h-24 w-full rounded-xl border border-line bg-mist/55 px-3 py-3 text-sm outline-none focus:border-ink" /></label><label className="block text-sm font-bold text-ink">Answer<textarea required value={card.a} onChange={(event) => setCard({ ...card, a: event.target.value })} className="mt-2 min-h-24 w-full rounded-xl border border-line bg-mist/55 px-3 py-3 text-sm outline-none focus:border-ink" /></label><div className="flex justify-end gap-3 pt-2"><button type="button" className="button-secondary" onClick={() => setAdding(false)}>Cancel</button><button disabled={saving} className="button-primary" type="submit">{saving ? 'Saving…' : 'Save card'} <ArrowRight size={16} /></button></div></form></motion.section></div>}
  </div>;
}
