import { useEffect, useState } from 'react';
import { CircleUserRound, KeyRound, Palette, ShieldCheck } from 'lucide-react';

export default function Settings() {
  const [name, setName] = useState<string | null>(null);
  useEffect(() => { fetch('/api/user').then((r) => r.json()).then((data) => setName(data.name ?? null)).catch(() => undefined); }, []);
  const initials = name?.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
  return <div className="page page-enter max-w-5xl space-y-5"><section><p className="eyebrow">Workspace settings</p><h1 className="display-title mt-4 text-5xl sm:text-6xl">Keep it yours.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-slate-600">A few useful details about how this local study space is configured.</p></section><div className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><aside className="panel p-4">{[[CircleUserRound, 'Profile'], [Palette, 'Interface'], [ShieldCheck, 'Privacy']].map(([Icon, label], index) => { const ItemIcon = Icon as typeof CircleUserRound; return <div key={String(label)} className={`flex min-h-12 items-center gap-3 rounded-xl px-3 text-sm font-bold ${index === 0 ? 'bg-sun text-ink' : 'text-slate-500'}`}><ItemIcon size={18} />{label}</div>; })}</aside><section className="panel p-6 sm:p-8"><p className="eyebrow">Profile</p><div className="mt-7 flex flex-col gap-5 border-b border-line pb-7 sm:flex-row sm:items-center"><div className="grid h-20 w-20 place-items-center rounded-[1.5rem] bg-sun font-display text-2xl font-bold text-ink">{initials ?? <CircleUserRound size={26} />}</div><div><h2 className="section-title text-2xl">{name ?? 'No display name set'}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{name ? 'Shown in your personal learning space.' : 'Add USER_NAME to your environment if you would like a name shown in the interface.'}</p></div></div><div className="mt-7 rounded-2xl bg-mist/70 p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white text-ink shadow-sm"><KeyRound size={18} /></div><div><p className="text-sm font-extrabold text-ink">Environment-managed profile</p><p className="mt-1 text-xs text-slate-500">Changes take effect after restarting the server.</p></div></div><pre className="mt-5 overflow-x-auto rounded-xl bg-ink px-4 py-3 font-mono text-xs text-mint">USER_NAME="Your name"</pre></div></section></div></div>;
}
