import { FormEvent, useEffect, useRef, useState } from 'react';
import { ArrowUp, BookOpen, BrainCircuit, Check, MessageCircle, Send, Sparkles, UserRound } from 'lucide-react';

type Message = { role: 'user' | 'model'; content: string };
type Card = { id: number; tag: string; q: string; mastery: number };
type Course = { title: string; outline: Array<{ title: string; description: string; status: string }> };

export default function StudySession() {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [course, setCourse] = useState<Course | null>(null); const [cards, setCards] = useState<Card[]>([]); const [sessionCount, setSessionCount] = useState(0); const endRef = useRef<HTMLDivElement>(null);
  useEffect(() => { fetch('/api/context').then((r) => r.json()).then((data) => { setCourse(data.course ?? null); setCards(data.flashcards ?? []); setSessionCount(data.sessionCount ?? 0); }).catch(() => undefined); }, []);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, loading]);
  const send = async (event: FormEvent) => { event.preventDefault(); const message = input.trim(); if (!message || loading) return; setInput(''); setError(null); setMessages((items) => [...items, { role: 'user', content: message }]); setLoading(true); try { const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message, history: messages }) }); if (!response.ok) throw new Error('Chat failed'); const data = await response.json(); setMessages((items) => [...items, { role: 'model', content: data.reply }]); if (data.newFlashcardAdded && data.newFlashcard) setCards((items) => [data.newFlashcard, ...items]); } catch { setError('Your message was not sent. Try again.'); } finally { setLoading(false); } };
  return <div className="page page-enter"><div className="grid min-h-[calc(100vh-130px)] gap-5 xl:grid-cols-[260px_minmax(0,1fr)_280px]">
    <aside className="panel hidden p-5 xl:block"><p className="eyebrow">Course map</p>{course ? <><h1 className="mt-4 font-display text-2xl font-bold tracking-[-.055em] text-ink">{course.title}</h1><div className="mt-8 space-y-5">{course.outline.map((item) => <div key={item.title} className="relative pl-6"><span className={`absolute left-0 top-1 h-3 w-3 rounded-full ${item.status === 'completed' ? 'bg-mint' : item.status === 'active' ? 'bg-sun shadow-[0_0_0_4px_rgba(255,212,107,.22)]' : 'bg-line'}`}>{item.status === 'completed' && <Check size={10} className="absolute -left-[1px] -top-[1px]" />}</span><p className="text-sm font-extrabold text-ink">{item.title}</p>{item.description && <p className="mt-1 text-xs leading-5 text-slate-500">{item.description}</p>}</div>)}</div></> : <div className="mt-6 rounded-2xl bg-mist/65 p-5"><BookOpen size={20} /><p className="mt-4 text-sm font-bold text-ink">No course selected.</p><p className="mt-1 text-sm leading-6 text-slate-600">You can still begin a conversation, or add a source from the dashboard.</p></div>}</aside>
    <section className="panel flex min-h-[620px] flex-col"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-line px-5 py-5 sm:px-7"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-sun text-ink"><BrainCircuit size={19} /></div><div><p className="font-display text-lg font-bold tracking-[-.05em] text-ink">{course?.title ?? 'Open study session'}</p><p className="font-mono text-[9px] uppercase tracking-[.1em] text-slate-500">Session {sessionCount || 'new'}</p></div></div><span className="rounded-full bg-mist px-3 py-1.5 font-mono text-[9px] uppercase tracking-wider text-slate-500">Socratic mode</span></header>
      <div className="flex-1 space-y-6 overflow-y-auto px-5 py-7 sm:px-8">{messages.length === 0 && !loading && <div className="mx-auto mt-12 max-w-md text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-sky/25 text-ink"><MessageCircle size={24} /></div><h2 className="mt-6 font-display text-3xl font-bold tracking-[-.06em] text-ink">What are you working through?</h2><p className="mt-3 text-sm leading-7 text-slate-600">Ask about an idea, unpack a passage, or test your understanding. The conversation begins when you do.</p></div>}{messages.map((message, index) => <article key={`${message.role}-${index}`} className={`flex gap-3 ${message.role === 'user' ? 'justify-end' : ''}`}><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${message.role === 'user' ? 'order-2 bg-ink text-white' : 'bg-mint text-ink'}`}>{message.role === 'user' ? <UserRound size={16} /> : <Sparkles size={16} />}</div><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-7 ${message.role === 'user' ? 'order-1 rounded-tr-sm bg-ink text-white' : 'rounded-tl-sm bg-mist/75 text-ink'}`}>{message.content}</div></article>)}{loading && <div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-mint"><Sparkles size={16} /></div><div className="rounded-2xl bg-mist px-4 py-3"><span className="inline-flex gap-1"><i className="h-1.5 w-1.5 rounded-full bg-slate-400 animate-pulse" /><i className="h-1.5 w-1.5 rounded-full bg-slate-400 animate-pulse [animation-delay:150ms]" /><i className="h-1.5 w-1.5 rounded-full bg-slate-400 animate-pulse [animation-delay:300ms]" /></span></div></div>}{error && <p className="rounded-xl bg-coral/20 px-4 py-3 text-sm font-semibold text-ink" role="alert">{error}</p>}<div ref={endRef} /></div>
      <form onSubmit={send} className="border-t border-line p-4 sm:p-5"><label className="flex items-end gap-2 rounded-[1.35rem] border border-ink/12 bg-white/75 p-2 pl-4 shadow-sm focus-within:border-ink/35"><textarea value={input} onChange={(event) => setInput(event.target.value)} disabled={loading} rows={1} placeholder="Ask a question in your own words…" className="max-h-32 min-h-10 flex-1 resize-none border-0 bg-transparent py-2 text-sm leading-6 text-ink outline-none placeholder:text-slate-400" /><button disabled={!input.trim() || loading} className="grid h-11 w-11 place-items-center rounded-2xl bg-ink text-white transition-transform hover:scale-105 disabled:opacity-35" aria-label="Send message"><ArrowUp size={19} /></button></label></form>
    </section>
    <aside className="panel hidden p-5 xl:block"><div className="flex items-center justify-between"><p className="eyebrow">Active deck</p><span className="font-mono text-[10px] text-slate-500">{cards.length}</span></div>{cards.length ? <div className="mt-6 space-y-3">{cards.slice(0, 5).map((card) => <article key={card.id} className="rounded-2xl bg-mist/65 p-4"><div className="flex justify-between gap-3"><span className="font-mono text-[9px] uppercase tracking-wider text-slate-500">{card.tag}</span><span className="font-mono text-[9px] text-slate-500">{card.mastery}%</span></div><p className="mt-3 line-clamp-3 text-sm font-bold leading-6 text-ink">{card.q}</p><div className="progress-track mt-4"><div className="progress-fill" style={{ width: `${card.mastery}%` }} /></div></article>)}</div> : <div className="mt-6 rounded-2xl bg-mist/65 p-5"><p className="text-sm font-bold text-ink">No cards in view.</p><p className="mt-1 text-sm leading-6 text-slate-600">Cards created from this session will appear here.</p></div>}</aside>
  </div></div>;
}
